require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_KEY
);

const tips = [
  // ─── REDSTONE ───────────────────────────────────────────────
  { category: 'Redstone', title: '[BEGINNER] Understanding Redstone Dust', content: 'Redstone dust carries a signal up to 15 blocks before it fades. Each block it travels reduces the signal strength by 1. Use Redstone Repeaters to boost the signal back to 15 and extend your circuits indefinitely. Repeaters also lock signal direction, which is useful for preventing backflow. Place them every 15 blocks on long runs. This is the most fundamental concept in all of Redstone engineering.' },
  { category: 'Redstone', title: '[BEGINNER] Basic Redstone Door Lock', content: 'Combine a pressure plate on the inside with a button on the outside to make a simple door entry system. Add a NOT gate (torch on a block) so that the inside pressure plate keeps the door open as long as you stand on it. This is one of the first practical Redstone builds every player should learn — it keeps mobs out while letting you in quickly.' },
  { category: 'Redstone', title: '[BASIC] Hopper Minecart Item System', content: 'Hopper minecarts are 9x faster than regular hoppers and can pull items through other blocks. Build a loop of powered rail and detector rail under your storage system. The hopper minecart constantly rides the loop, collecting items from chests above. Use detector rails to trigger powered rails and keep it moving. This is the backbone of many large-scale automatic storage systems in the game.' },
  { category: 'Redstone', title: '[BASIC] Piston Extender for Hidden Doors', content: '2x2 piston doors are iconic hidden entrances. Use 6 sticky pistons arranged in two columns of 3. A single lever or button triggers both columns simultaneously using Redstone timing with repeaters. Add a 1-tick delay on one side to prevent jamming. Conceal the mechanism behind walls and cover the door with matching blocks. This is one of the most satisfying Redstone builds you can make in survival.' },
  { category: 'Redstone', title: '[MOST IMPORTANT] Always Add an Off Switch', content: 'Every Redstone clock, farm, or automated machine must have an off switch — no exceptions. Running clocks cause server lag, especially on multiplayer servers. Use a lever to interrupt the circuit or place a Redstone torch as a kill switch. For mob farms, an off switch prevents overflow. For item sorters, it prevents hopper lag. The off switch is not optional — it is a core design principle of good Redstone engineering.' },
  { category: 'Redstone', title: '[PRO TIP] Quasi-Connectivity for Instant Pistons', content: 'Quasi-connectivity is a Java Edition mechanic where a piston activates if the block directly above its head receives a Redstone signal — even if the piston itself does not. This allows 0-tick piston pulses that move blocks nearly instantaneously. Use BUD (Block Update Detector) switches to exploit this. Quasi-connectivity powers flying machines, instant doors, and many competition-level builds. It is one of the most powerful unintended mechanics in the game.' },
  { category: 'Redstone', title: '[PRO TIP] Comparator Subtraction Mode', content: 'Redstone Comparators in subtraction mode output the difference between the back signal and the side signal. This is essential for reading container fullness — a chest with items outputs a signal of 1–15 based on how full it is. Use comparator subtraction to create conditional logic: only trigger a system when a chest reaches a certain fill level. This technique powers automatic smelting arrays, item overflow detectors, and smart storage routing systems.' },
  { category: 'Redstone', title: '[BASIC] T Flip-Flop Toggle Circuit', content: 'A T flip-flop converts a momentary button press into a sustained on/off toggle. Build it with two Redstone torches, two repeaters set to 1 tick, and some Redstone dust in a loop. Every button press flips the output state. This is essential for any build where you want a button (not a lever) to toggle something like a door, a lamp, or a farm on and off. It is a fundamental circuit that every Redstone builder uses constantly.' },
  { category: 'Redstone', title: '[BEGINNER] Daylight Sensor Lighting', content: 'Daylight sensors output a Redstone signal based on the time of day. In inverted mode (right-click the sensor), it outputs a signal at night and nothing during the day. Connect an inverted daylight sensor to glowstone or sea lanterns around your base for automatic lighting that turns on at dusk and off at dawn. No switches needed. This is one of the easiest and most useful Redstone builds for any base.' },
  { category: 'Redstone', title: '[PRO TIP] Flying Machines with Slime Blocks', content: 'Slime blocks move adjacent blocks when pushed by a piston. Chain two pistons facing each other — one pushes, the other retracts — and the structure moves in one direction forever. Add an observer facing the back piston to detect its retraction and trigger the front piston. Flying machines can carry passengers, harvest farms, and even carry TNT for automated mining. They are one of the most creative and complex Redstone builds achievable in vanilla Minecraft.' },

  // ─── COMBAT ─────────────────────────────────────────────────
  { category: 'Combat', title: '[BEGINNER] Critical Hit Timing', content: 'Critical hits deal 150% damage and are triggered by attacking while falling — not just jumping, but actually on the way down. Watch for the star particles that appear on a successful crit. Combine crits with the attack cooldown indicator (the sword icon below your hotbar) — wait for it to fill to 100% before striking. Mixing full-charge attacks with crits maximizes your DPS against any mob or player.' },
  { category: 'Combat', title: '[BEGINNER] How to Fight Creepers', content: 'Creepers are most dangerous in close range — they need 1.5 seconds of uninterrupted proximity to explode. The safest technique: sprint toward the creeper, land one hit, then immediately sprint backward to create distance. Repeat. The hit causes knockback that resets the fuse. Use a sword with Knockback enchantment to push them further back. Never corner yourself against a creeper and always listen for the hissing sound cue.' },
  { category: 'Combat', title: '[BASIC] Bow vs Crossbow — When to Use Each', content: 'Bows fire faster with a full charge (1 second) and benefit from the Infinity enchantment to save arrows. Crossbows deal more damage per shot and can be pre-loaded, making them better for ambushes. Use bows for sustained ranged combat against moving targets. Use crossbows loaded with Fireworks for AOE splash damage against groups. Crossbows with Multishot hit three targets at once — devastating in PvP hallways and mob corridors.' },
  { category: 'Combat', title: '[BASIC] Armor Enchantment Priority', content: 'For maximum survivability, prioritize Protection IV on all four armor pieces — this is better than mixing Fire Protection, Blast Protection, and Projectile Protection because the 4% damage reduction stacks to 64% total across all slots. Add Feather Falling IV to boots as a second priority. Then add Thorns III to the chestplate to punish attackers. Mending on all pieces ensures your armor repairs itself with XP during normal play.' },
  { category: 'Combat', title: '[MOST IMPORTANT] Never Fight on Half a Heart', content: 'Knowing when to retreat is the most important combat skill. If you drop below 4 hearts in a fight, break off immediately — one unlucky hit or explosion ends your run. Carry Golden Apples for emergency healing and know your escape route before engaging. In the Nether especially, lava and mobs together are lethal. Dying in Hardcore or losing a full inventory deep underground from fighting at low health is the most avoidable mistake in Minecraft.' },
  { category: 'Combat', title: '[PRO TIP] Axe vs Sword in PvP', content: 'Axes deal more damage than swords and disable shields for 5 seconds on a hit. However, axes have a longer cooldown. In PvP, alternate between axe hits to break shields and sword hits while their shield is down. An axe with Sharpness V and a sword with Sweeping Edge III together cover all scenarios. The axe beats shield-users; the sword beats unshielded opponents with its faster attack speed and sweep damage.' },
  { category: 'Combat', title: '[PRO TIP] End Crystal PvP Trapping', content: 'End Crystals placed on obsidian or bedrock deal up to 64 hearts of damage when destroyed — enough to one-shot any player regardless of armor. In PvP, place crystals near an opponent and break them instantly using an axe or arrow. Surround the placement with obsidian to prevent them from breaking your crystal before you do. This technique is the highest skill-cap PvP mechanic in the game and is used in top-level crystal PvP.' },
  { category: 'Combat', title: '[BASIC] Potions Every Player Should Carry', content: 'Always carry: Instant Health II (emergency burst heal), Strength II (60 seconds of +6 damage per hit), Speed II (faster escape and gap-closing), and Fire Resistance (essential in Nether and against blazes). Splash potions of Weakness are crucial for curing zombie villagers. Brew potions in bulk — keep a chest of at least 16 of each type before entering dangerous areas. Potions are the biggest damage multiplier available to any player.' },
  { category: 'Combat', title: '[BEGINNER] Mob Aggro Ranges', content: 'Different mobs have different detection ranges. Zombies and skeletons detect you within 16 blocks in low light. Endermen aggro only when looked at directly (avoid their eyes). Spiders are neutral in daylight but hostile at night. Wolves aggro permanently if you hit them. Piglins become hostile if you attack one — the entire nearby group joins the fight. Understanding aggro ranges lets you navigate dangerous areas without triggering unnecessary fights.' },
  { category: 'Combat', title: '[PRO TIP] Totem of Undying Strategies', content: 'A Totem of Undying in your offhand saves your life once by restoring 1 heart and granting Regeneration II and Absorption IV for 5 seconds. The key is hand management — keep the totem in your offhand even during mining and building. After it activates, immediately consume a golden apple while the absorption is active. Farm Evokers in Woodland Mansions or raids for a steady supply. In hardcore mode, totems are the only death prevention available.' },

  // ─── BUILDING ───────────────────────────────────────────────
  { category: 'Building', title: '[BEGINNER] The 60/30/10 Color Rule', content: 'Professional builders use the 60/30/10 rule: 60% of your build uses a dominant material (like stone brick), 30% uses a secondary material (like cobblestone or andesite), and 10% uses an accent material (like iron bars or wood trim). This prevents your build from looking monotonous. Vary the ratios slightly in different sections to create depth. This single principle elevates beginner builds to look intentional and polished.' },
  { category: 'Building', title: '[BEGINNER] Avoid Flat Walls', content: 'Flat, single-material walls are the most common sign of a beginner build. Break them up with pilasters (columns of a different material), recesses (dig 1 block back in sections), and window cutouts. Add a different material for every 4–5 blocks of height to create visual layers. Even just alternating stone brick with cracked stone brick breaks the monotony significantly. Depth and texture in walls are what separate average builds from impressive ones.' },
  { category: 'Building', title: '[BASIC] Roof Types and When to Use Them', content: 'There are four main roof types: flat (modern/industrial builds), gabled (classic houses), hip (cottages/Japanese style), and dome (towers/temples). Staircase blocks are essential for sloped roofs — use them in layers, each stepped 1 block back, for a natural slope. Add upside-down stairs at the base of a gabled roof for an overhang. Mix roof types on complex builds — a main gabled roof with smaller dormer windows adds realism and complexity.' },
  { category: 'Building', title: '[BASIC] Interior Design Essentials', content: 'Good interiors tell a story. Every room needs a purpose: kitchen (smoker, barrels, item frames with food), bedroom (bed, chest, lantern), library (bookshelves, lectern, carpet), workshop (crafting table, anvil, grindstone). Use item frames on walls as paintings. Hang banners as tapestries. Place armor stands with armor sets as decorative statues. Add potted plants (bamboo, ferns, flowers) in corners for life. Avoid leaving rooms empty — fill every wall with functional or decorative items.' },
  { category: 'Building', title: '[MOST IMPORTANT] Plan Before You Build', content: 'The biggest mistake builders make is starting without a plan. Before placing a single block, sketch the footprint on paper or flat ground with a different material. Mark out the walls, rooms, and entry points. Decide on height and material palette before starting. Building without a plan leads to proportion errors, awkward room sizes, and structures that need to be torn down halfway through. 10 minutes of planning saves hours of rebuilding.' },
  { category: 'Building', title: '[PRO TIP] Custom Trees for Natural Landscapes', content: 'Vanilla trees look artificial in detailed builds. Build custom trees by hand: start with a 2x2 trunk of dark oak logs, branch out at Y+5 with single log arms angled upward, then place leaf blocks in organic clusters (avoid perfect spheres). Mix jungle leaves with oak leaves for color variation. Add vines hanging from branches. Use brown mushroom caps as large canopy sections in dark forests. Custom trees make the difference between a landscape that looks generated and one that looks crafted.' },
  { category: 'Building', title: '[PRO TIP] Mixing Block Palettes for Texture', content: 'Top builders never use a single block type for large surfaces. For a stone castle wall, mix: stone brick, cracked stone brick, mossy stone brick, and andesite in a roughly random pattern (30% primary, 20% each variant). For wood builds, mix oak, dark oak, and stripped logs. For sandy areas, mix sand, sandstone, coarse dirt, and gravel. This mixing technique, called block palette variation, is what makes professional builds look photorealistic from a distance.' },
  { category: 'Building', title: '[BASIC] Lighting Without Breaking Immersion', content: 'Exposed torches and glowstone break the atmosphere of detailed builds. Hide light sources inside: place sea lanterns under carpet (they still emit light through it), put glowstone behind paintings or inside walls with glass panes, use shroomlights inside custom trees, and hang lanterns from chains under roof overhangs. In modern builds, use end rods embedded in walls as recessed lighting. The light source should be felt, not seen.' },
  { category: 'Building', title: '[BEGINNER] Use Stairs and Slabs Everywhere', content: 'Stairs and slabs are the most powerful shaping tools in Minecraft. Use upside-down stairs to create curved arches, corbels, and overhangs. Layer slabs to add half-block height offsets. Combine stair and slab steps to create smooth transitions between heights. Use stair blocks as seats, shelves, and decorative trim. Nearly every element of a polished build — roofs, arches, furniture, pathways — relies heavily on stairs and slabs rather than full blocks alone.' },
  { category: 'Building', title: '[PRO TIP] Landscaping Techniques Around Builds', content: 'A stunning build on flat, untouched terrain looks out of place. Integrate your build into the landscape: raise the terrain around foundations so the build appears to grow from the ground. Add custom pathways of gravel, stone slabs, and grass using the stepping-stone pattern. Plant custom trees at varying heights nearby. Add a stream or pond using source blocks and clay banks. For castles, create a moat. For farms, add field rows. The landscape is 50% of any build\'s visual impact.' },

  // ─── FARMING ────────────────────────────────────────────────
  { category: 'Farming', title: '[BEGINNER] Bone Meal for Fast Crops', content: 'Bone meal instantly advances most crops by several growth stages. It works on wheat, carrots, potatoes, beetroot, melons, pumpkins, sugarcane (in some versions), and saplings. Craft it from bones dropped by skeletons or from a composter filled with plant materials. Keep a stack of bone meal in your hotbar while farming to instantly harvest mature crops. A composter next to your farm creates a closed loop — put leftover seeds in, get bone meal out.' },
  { category: 'Farming', title: '[BEGINNER] Hydrated Farmland Basics', content: 'Crops only grow on farmland that is hydrated (dark brown color). A single water source block hydrates all farmland within a 4-block radius (including diagonals). The most efficient layout is a 9x9 field with a single water block in the center — this hydrates all 80 surrounding farmland tiles. Use a hoe on dirt to create farmland. Placing a slab over your water source prevents mobs and players from falling in and prevents evaporation.' },
  { category: 'Farming', title: '[BASIC] Sugarcane Farm Design', content: 'Sugarcane is essential for paper and sugar. Build an efficient farm by placing sugarcane on a single row of sand or dirt next to a water channel. Place observers facing the sugarcane — when it grows to 3 blocks tall, the observer detects the change and fires a piston that breaks the top two blocks, leaving the base intact to regrow. Run a water stream behind the pistons to carry the drops to a collection hopper. This design produces sugarcane passively with zero effort.' },
  { category: 'Farming', title: '[BASIC] Efficient Animal Breeding', content: 'Each animal has a specific breeding item: wheat (cows, sheep), carrots/potatoes/beetroot (pigs), seeds (chickens), sweet berries (foxes), bamboo (pandas). After breeding, animals have a 5-minute cooldown. To maximize output, keep 2 of each animal in small pens (2x2 is enough) and breed them every 5 minutes. Babies take 20 minutes to grow — feed them their breeding item to halve growth time. Always keep a surplus of at least 10 of each animal to avoid bottlenecks.' },
  { category: 'Farming', title: '[MOST IMPORTANT] Build a Composting System Early', content: 'A composting system is one of the highest-value early-game builds. Place a composter next to each of your crop farms. Every failed crop, excess seed, and unwanted plant goes in. Each fill of the composter produces 1 bone meal. Bone meal accelerates all crop growth, which means more food sooner, which means more materials for the composter — a self-sustaining loop. This system eliminates food scarcity in early survival and provides infinite bonemeal for tree and crop acceleration.' },
  { category: 'Farming', title: '[PRO TIP] Zero-Tick Farms (Bedrock)', content: 'On Bedrock Edition, zero-tick farming exploits random tick acceleration. Place a piston that instantly pushes and retracts on farmland — this triggers the crop\'s random tick multiple times in a single game tick, causing it to grow almost instantly. Connect a clock circuit to run the pistons continuously. A zero-tick sugarcane or cactus farm produces resources hundreds of times faster than a standard design. Combine with auto-collection using hoppers for fully passive, ultra-fast production.' },
  { category: 'Farming', title: '[PRO TIP] Villager Trading for Infinite Emeralds', content: 'Farmers trade crops for emeralds. Set up a villager crop trading system: build a villager farm with Farmer villagers (brown coat), link them to your crop farm, and they automatically harvest and replant crops. Trade the collected crops to the Farmer for emeralds, then trade those emeralds to Librarians for enchanted books. This creates an infinite emerald loop from crop farming. Lock in good trades by trading with the villager until their prices lock at minimum.' },
  { category: 'Farming', title: '[BASIC] Passive XP from Smelting Farms', content: 'Smelting items in a furnace stores XP that is collected when you take the output. Build an auto-smelter with hoppers feeding raw materials in from the top and fuel (kelp or bamboo from farms) from the side. A collection hopper at the bottom sends items to a chest. When you retrieve items from the output chest, you collect all stored XP at once — potentially thousands of levels if left running for a long time. Kelp farms are the most efficient fuel source for this setup.' },
  { category: 'Farming', title: '[BEGINNER] Nether Wart for Potions', content: 'Nether Wart is the base ingredient for almost every potion in the game. It only grows on Soul Sand and does not need water or light. Plant it in a room next to your brewing stand. Nether Wart does not grow faster with bone meal, but it grows quickly on its own. Keep a large supply — you need it in bulk for any serious potion brewing operation. Collect it from Nether Fortresses and replant immediately to build your supply.' },
  { category: 'Farming', title: '[PRO TIP] Enderman XP Farm for Fast Leveling', content: 'An Enderman farm in The End (built above the main island at Y=188 or higher) produces the highest XP rates in the game. Endermen spawn naturally in The End and drop 5 XP each. Build a dark platform and funnel Endermen into a drop shaft using water streams. A fall of 23 blocks brings them to 1 HP, then kill them with one hit. A well-designed Enderman farm yields 30+ levels per minute, making enchanting and anvil repair trivially easy to maintain.' },

  // ─── SURVIVAL ───────────────────────────────────────────────
  { category: 'Survival', title: '[BEGINNER] First Night Checklist', content: 'Day 1 in survival has a clear priority order: punch wood (64 logs minimum), craft a crafting table, make wooden tools, find and mine stone (32+), upgrade to stone tools, mine coal (32+), find or make a shelter before dark. Do NOT mine down on day 1. Build a small dirt or wood shelter above ground and place a door. Make a chest to store items, a furnace for food, and a bed if you find three wool before dark. This checklist ensures you survive the first night every time.' },
  { category: 'Survival', title: '[BEGINNER] Food Priority in Early Game', content: 'Food is your most important resource early on. Cooked meat is the most efficient food source: cooked steak restores 8 hunger and 12.8 saturation. Kill cows or pigs immediately on spawn and cook the meat in your furnace. Bread is a good alternative if you find wheat villages. Avoid raw food — it restores less saturation, meaning you get hungry faster. Always keep at least half a stack of cooked food before going underground or exploring far from your base.' },
  { category: 'Survival', title: '[BASIC] Strip Mining for Diamonds', content: 'Diamonds spawn most frequently at Y=-58 in 1.18+. Strip mine at this level by digging a main tunnel 2 blocks tall, then branching corridors every 3 blocks to either side. This pattern exposes the maximum number of blocks with minimum digging. Use a Fortune III pickaxe to multiply your diamond yield — Fortune III averages 2.2 diamonds per ore instead of 1. Bring torches every 8 blocks to prevent mob spawns in your tunnels. Always carry a water bucket for unexpected lava encounters.' },
  { category: 'Survival', title: '[BASIC] Villager Trading Setup', content: 'A trading hall is one of the best mid-game investments. Trap villagers and assign them to workstations (lectern = Librarian, smithing table = Toolsmith, etc.). Reroll trades by breaking and replacing the workstation until you get the enchanted book, tool, or trade you want. Level up each villager to Master level by trading repeatedly — Master Librarians sell the best enchanted books including Mending. Lock in prices by curing zombie villagers (splash weakness potion + golden apple) to get permanent discounts.' },
  { category: 'Survival', title: '[MOST IMPORTANT] Backup Your Base Location', content: 'Write down your base coordinates the moment you establish them — X, Y, Z and your biome. A death without a bed or map means losing your base permanently in a large world. Set your spawn immediately by sleeping in a bed on your first night at base. In later game, craft a map and mark key locations. Set up lodestone compasses pointing to base, your mine entrance, and any villages or structures nearby. Losing your base to disorientation is one of the most demoralizing things that can happen in survival.' },
  { category: 'Survival', title: '[PRO TIP] Elytra Travel with Fireworks', content: 'Elytra with Firework Rockets is the fastest transport in the game — faster than horses, boats, or any other method. Craft rockets with one gunpowder and one paper (no star needed) for cheap boosting rockets. Sprint-jump and immediately equip your elytra to launch from the ground without a ledge. Use the F5 view to check your angle and avoid obstacles. Keep 3 stacks of rockets in your inventory for long journeys. The Riptide trident in rain is the only method that competes for speed.' },
  { category: 'Survival', title: '[PRO TIP] Beacon Network for Permanent Buffs', content: 'A tier 4 Beacon (requires 164 iron/gold/diamond/netherite blocks) provides permanent Haste II, Speed II, Strength II, Regeneration II, or Jump Boost II in a 50-block radius. For a mining operation, place a Haste II beacon at the entrance to your mine — Haste II with an Efficiency V pickaxe breaks stone instantly. For your base, Speed II eliminates the need for sprint. Multiple beacons with different effects create a buffed zone around your entire base. The investment pays off within hours of use.' },
  { category: 'Survival', title: '[BASIC] Efficient XP Management', content: 'XP in Minecraft is fragile — you drop it all on death and it despawns after 5 minutes. Use a dedicated XP farm (mob spawner or Enderman farm) to level up to 30 before every enchanting session. Keep a Mending rod or sword in your hotbar to absorb ambient XP and repair your tools passively. Never enchant at low XP levels — always wait for level 30 for the best rolls. Store excess levels by enchanting books to prevent losing XP to a death at high levels.' },
  { category: 'Survival', title: '[BEGINNER] How to Find Your Biome', content: 'Use the F3 debug screen (Java) or the coordinates display (Bedrock) to see your current biome name. Deserts and plains generate near spawn in most seeds. To find specific biomes, use the /locatebiome command in Java (even in survival with cheats enabled). For mesa (badlands) biomes — the best source of gold — look for distinctive orange-red terrain. Mushroom islands always generate in oceans. Jungles generate adjacent to savanna biomes. Knowing your biome determines what resources and structures are nearby.' },
  { category: 'Survival', title: '[PRO TIP] Raid Farm for Maximum Loot', content: 'Raid farms generate the best loot in the game passively: emeralds, enchanted books, totems, saddles, and crossbows. Trigger a raid by entering a village with the Bad Omen effect (kill an Illager captain). Build a raid farm by funneling raiders into a kill zone using the village\'s bell radius as the spawn trigger. A well-built raid farm produces 30+ emeralds and multiple totems per raid. Complete raids regularly for the Hero of the Village discount effect, which makes all villager trades cheaper for several days.' },
];

async function seed() {
  // Get the CraftMaster user id
  const { data: users, error: userErr } = await supabase
    .from('users')
    .select('id')
    .eq('username', 'CraftMaster')
    .limit(1);

  if (userErr || !users?.length) {
    console.error('Could not find CraftMaster user:', userErr);
    process.exit(1);
  }

  const userId = users[0].id;
  console.log(`Found CraftMaster with id=${userId}`);

  // Insert all tips
  const rows = tips.map(t => ({ ...t, user_id: userId }));
  const { data, error } = await supabase.from('tips').insert(rows).select('id, title');

  if (error) {
    console.error('Insert failed:', error);
    process.exit(1);
  }

  console.log(`Inserted ${data.length} tips:`);
  data.forEach(t => console.log(`  [${t.id}] ${t.title}`));
}

seed();
